### ISSUE TITLE
Améliorer les performances de l'upscaler

### ISSUE THREAD

**Issue by Aelerinya** [EIP-PixelUP/PU_Client#7]
- [ ] Trouver ce qui prend du temps dans le client actuel

- [ ] tester une implémentation en un autre langage #5 

- [ ] Ne pas utiliser OpenCV

- [ ] Utiliser une autre IA #4 

- [ ] Tester avec GPU #8
